### ISSUE TITLE
Search fo tests

### ISSUE THREAD

**Issue by jgardner04** [ppparihar/GoTestExplorer#15]
Love the test explorer but when I work on a project with a large number of tests and only want to run one, I have to scroll through the whole list. A nice feature would be the ability to search for a test by name.

**Comment by ppparihar** [comment]
@jgardner04 Thanks for writing here. let me check the feasibility of the feature. I will love to implement if it's feasible.

**Comment by jgardner04** [comment]
@ppparihar normally I would try to help but I don’t have the cycles at the moment! Keep up the great work.

**Comment by ppparihar** [comment]
@jgardner04 VS Code has native support for search and the same can be used to search our tests. Feel free to write back if you still have any feedback/suggestion.

![Search Test](https://user-images.githubusercontent.com/18534464/63078772-3d6c9980-bf5a-11e9-8198-85e1a44a788e.gif)

**Comment by diversemix** [comment]
When you apply the filter however it is only applied to the view - not to which tests are run. Which means after applying the filter and then clicking run tests - it runs the entire tests for the project (not the ones just filtered)
