### ISSUE TITLE
Explorer does not use the "go.testFlags" from settings

### ISSUE THREAD

**Issue by johnpan** [ppparihar/GoTestExplorer#17]
Trying to avoid the known error (here ([https://github.com/golang/go/issues/28065])) "gcc": executable file not found in $PATH, I used 
```
"go.testFlags": [
        "-vet=off"
    ]
```
but reading the output while testing, the tool does not add the test flags:

```
Running tool: /usr/local/go/bin/go test  -timeout 30s -run ^TestAreSpecificOdds$
# runtime/cgo
exec: "gcc": executable file not found in $PATH
FAIL	caching/parsers [build failed]
FAIL
Error: Tests failed.
```

**Comment by bbrks** [comment]
An inferred workspace GOPATH is not being picked up when using the `"go.inferGopath": true` setting either. This might be closely related.
