### ISSUE TITLE
Need help configuring VS Code so `Debug Test` option works

### ISSUE THREAD

**Issue by johnvoelk** [ppparihar/GoTestExplorer#23]
I love this VSCode extension but currently I can only run tests.  I'm able to debug my Go code but not my Go tests using the `Debug Test` context menu option.  Any help would be greatly appreciated!

I'm assuming I'm missing some .vscode configuration.  Below are the contents of my launch.json file: 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/main.go",
            "envFile": "${workspaceFolder}/.vscode/dev.env",
            "args": [],
        }
    ]
}
```

**Comment by ppparihar** [comment]
@johnvoelk  currently this extension has no support to `debug Test`.
Can you please check https://github.com/golang/vscode-go/blob/master/docs/debugging.md if this can help you.
