### ISSUE TITLE
Question - Test All 

### ISSUE THREAD

**Issue by hossta** [ppparihar/GoTestExplorer#28]
Hello - With the new release 0.1.12, I'm just wondering if anyone has had problems running the Test All and individual tests from the Go Test Explorer menu. The test shows the busy circle icon, but the tests never complete. I downgraded to the previous version of Go Test Explorer, and the Test All completes okay. 
Thanks for any thoughts on this question.

**Comment by nirmalpatel94** [comment]
@hossta saw the same issue on my machine

**Comment by ppparihar** [comment]
@hossta  and @nirmalpatel94  thank you for reporting here. Do you see any error on the console?

**Comment by hossta** [comment]
Thank you @nirmalpatel94 and @ppparihar for the comments.
Thanks for the question. I do not see any error on the debug console.
I did notice this message is missing. The message indicating it is running is not in the Output panel: "Running tool: c:\go\bin\go.exe test ...

**Comment by ppparihar** [comment]
It has been fixed as part of v0.1.13 release.

**Comment by hossta** [comment]
@ppparihar Thank you so much!
